export const listingInfo = {
    title: "About the Listing",
    sections: [
        {
            heading: 'Projects',
            body: "In the main section are listings. These are generated by project creators who are looking for help from contributors." 
    },
    {
        heading: "Search and Tags", 
        body: "CoLab allows two types of search. You can search by project name using the search bar in the upper left corner or you can search using the tag buttons in the listing. Using text search if you know the exact name of the project you are looking for. Enable tag search if you are looking for project that suit your interest. CoLab has three different types of tags. You can read more about that in the FAQ."
    },
    {
        heading: "Votes",
        body: "Any registered user can upvote a project. Projects with higher votes appear higher in the search. This is a temporary, crude system that will eventually be replaced by a more sophistated reputation system. If you're interested, there's more on this in the FAQ."
    }, 
    ]
}